NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import PostsView

urlpatterns = [
    path('', PostsView.as_view()),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('articles/', include('articles.urls')),
    path('profile/', include('profile.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

NewsPortal/news/urls.py
from django.urls import path
from .views import PostsView, PostDetailView, PostsSearchView, PostAddView, PostUpdateView, PostDeleteView, subs_add


urlpatterns = [
    path('', PostsView.as_view()),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('search/', PostsSearchView.as_view()),
    path('add/', PostAddView.as_view()),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('subsadd/<int:pk>', subs_add, name='subsadd'),
]

NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)

    def update_rating(self):
        post_rating = Post.objects.filter(author=self).values('rating')
        pr = sum(pst['rating'] for pst in post_rating) * 3

        comm_rating = Comment.objects.filter(author=self.user).values('rating')
        cr = sum(com['rating'] for com in comm_rating)

        auth_rating = Post.objects.filter(author=self).values('comments__rating')
        ar = 0
        for aut in auth_rating:
            if aut['comments__rating']:
                ar += aut['comments__rating']

        self.rating = pr + cr + ar
        self.save()

    def __str__(self):
        return f'{self.user.username}'


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    subscribers = models.ManyToManyField(User, through='UserCategory')

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    article = 'ART'
    news = 'NWS'

    TYPE = [
        (news, 'Новость'),
        (article, 'Статья'),
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=3, choices=TYPE, default=news)
    time_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    head = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.text) < 125:
            return self.text[:] + '...'
        else:
            return self.text[:124] + '...'

    def get_absolute_url(self):
        if self.type == 'NWS':
            return f'/news/{self.id}'
        else:
            return f'/articles/{self.id}'



class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time_in = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class UserCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

NewsPortal/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
    News#
{% endblock title %}

{% block content %}
    <h4>
        {{ time_now | date:'d M Y' }}
    </h4>
    <hr>
    <p style="font-size: 1.5em; font-family: Georgia;">
        {{ post.head | censor}}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Дата публикации: {{ post.time_in | date:'d.m.Y H:i' }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Автор: {{ post.author.user.username }}
    </p>
    <p style="font-size: 1.2em; font-family: Georgia;">
        {{ post.text | censor }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Рейтинг: {{ post.rating }}
    </p>
{% endblock content %}

NewsPortal/templates/post_add.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
{% if update %}
    {% if is_type == 'NWS' %}
        News/Update
    {% else %}
        Articles/Update
    {% endif %}
{% else %}
    {% if is_type == 'NWS' %}
        News/Add
    {% else %}
        Articles/Add
    {% endif %}
{% endif %}
{% endblock title %}

{% block content %}
    <br/>
    {% if update %}
        <h1 align="center" style="font-family: Georgia;"><strong> Редактирование публикации </strong></h1>
    {% else %}
        <h1 align="center" style="font-family: Georgia;"><strong> Добавление публикации </strong></h1>
    {% endif %}
    <hr>
    <p style="font-size: 1.3em; font-family: Georgia;">
    {% if is_type == 'NWS' %}
        Тип публикации: Новость
    {% else %}
        Тип публикации: Статья
    {% endif %}
    </p>
    <hr>
    <p style="font-size: 1.3em; font-family: Georgia;">
        Заполните необходимые поля:
    </p>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        {% if update %}
            <input type="submit" value="Редактировать публикацию" style="width:250px" >
        {% else %}
            <input type="submit" value="Добавить публикацию" style="width:200px" >
        {% endif %}
    </form>
    <br/><br/>
{% endblock content %}

NewsPortal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
    {% if post.type == 'NWS' %}
        News/Delete
    {% else %}
        Articles/Delete
    {% endif %}
{% endblock title %}

{% block content %}
<br/>
<h1 align="center" style="font-family: Georgia;"><strong> Удаление публикации </strong></h1>
    <hr>
    <p style="font-size: 1.4em; font-family: Georgia;">
        Вы увены, что хотите удалить данную публикацию?
    </p>
    <br/>
    <p style="font-size: 1.3em; font-family: Georgia;"><strong>
        {{ post.head | censor}}
    </strong></p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Дата публикации: {{ post.time_in | date:'d.m.Y H:i' }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Тип публикации: {{ post.get_type_display }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Автор: {{ post.author.user.username }}
    </p>
<br/>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>

{% endblock content %}

NewsPortal/templates/post_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
    {% if post.type == 'NWS' %}
        News#
    {% else %}
        Articles#
    {% endif %}
{% endblock title %}

{% block content %}
<br/>
    <p style="font-size: 1.5em; font-family: Georgia;"><strong>
        {{ post.head | censor}}
    </strong></p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Дата публикации: {{ post.time_in | date:'d.m.Y H:i' }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Тип публикации: {{ post.get_type_display }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Автор: {{ post.author.user.username }}
    </p>
    <p style="font-size: 1.2em; font-family: Georgia;">
        {{ post.text | censor }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Рейтинг: {{ post.rating }}
    </p>
    <p style="font-size: 0.8em; font-family: Georgia;">
        Категории:&emsp;
         {% for cat in post_cat %}
            {{cat}}&emsp;
        {% endfor %}
    </p>
    {% if request.user == post.author.user %}
        <p  align="right">
            {% if post.type == 'NWS' %}
                <a href="{% url 'post_update' post.id %}" style="color: #6c757d; font-size: 0.8em;">Редактировать</a>&emsp;
                <a href="{% url 'post_delete' post.id %}" style="color: #6c757d; font-size: 0.8em;">Удалить</a>
            {% else %}
                <a href="{% url 'art_update' post.id %}" style="color: #6c757d; font-size: 0.8em;">Редактировать</a>&emsp;
                <a href="{% url 'art_delete' post.id %}" style="color: #6c757d; font-size: 0.8em;">Удалить</a>
            {% endif %}
        </p>
    {% endif %}
    <br/>
    {% if request.user.pk %}
    {% if subs %}
        <p style="font-size: 1.0em; font-family: Georgia;">
            Подпишитесь на дополнительные категории:
        </p>
        {% for key, value in subs.items %}
            <p style="font-size: 1.0em; font-family: Georgia;">
                {{value}} <button>
                              <a href="{% url 'subsadd' key %}" style="text-decoration: none"> Подписаться </a>
                          </button>
            </p>
        {% endfor %}
    {% else %}
        <p style="font-size: 1.0em; font-family: Georgia;">
            Вы подписаны на все категории данной публикации!
        </p>
    {% endif %}
    {% endif %}
    <br/><br/>
{% endblock content %}

NewsPortal/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
    {% if author %}
        My posts
    {% else %}
        All posts
    {% endif %}

{% endblock title %}

{% block content %}
    <br/>
    {% if author %}
        <h1 align="center" style="font-family: Georgia;"><strong> Мои публикации </strong></h1>
    {% else %}
        <h1 align="center" style="font-family: Georgia;"><strong> Все публикации </strong></h1>
    {% endif %}
    <hr>
    {% if posts %}
        <p style="font-size: 1em; font-family: Georgia;">
            Всего публикаций: {{ all }}
        </p>
        <p style="font-size: 0.8em; font-family: Georgia;">
            Показана страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </p>
        <br/>
        <table style="width: 100%; font-family: Georgia;">
            <tr>
                <th style="border-bottom: 3px solid #B9B29F; width:40%;padding-bottom: 10px;"> Заголовок </th>
                <th style="border-bottom: 3px solid #B9B29F; width:15%;padding-bottom: 10px;"> Тип<br/>публикации </th>
                <th style="border-bottom: 3px solid #B9B29F; width:15%;padding-bottom: 10px;"> Дата<br/>публикации </th>
                <th style="border-bottom: 3px solid #B9B29F; width:45%;padding-bottom: 10px;"> Содержание </th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td style="padding-top: 10px; padding-bottom: 15px">
                        {% if post.type == 'NWS' %}
                            <a href="{% url 'post_detail' post.id %}" style="text-decoration: none"> {{ post.head | censor}} </a>
                        {% else %}
                            <a href="{% url 'art_detail' post.id %}" style="text-decoration: none"> {{ post.head | censor}} </a>
                        {% endif %}
                        <br/>
                        {% if request.user == post.author.user %}
                            {% if post.type == 'NWS' %}
                                <a href="{% url 'post_update' post.id %}" style="color: #6c757d; font-size: 0.8em;">Редактировать</a>&emsp;
                                <a href="{% url 'post_delete' post.id %}" style="color: #6c757d; font-size: 0.8em;">Удалить</a>
                            {% else %}
                                <a href="{% url 'art_update' post.id %}" style="color: #6c757d; font-size: 0.8em;">Редактировать</a>&emsp;
                                <a href="{% url 'art_delete' post.id %}" style="color: #6c757d; font-size: 0.8em;">Удалить</a>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td style="padding-top: 10px; padding-bottom: 15px"> {{ post.get_type_display }} </td>
                    <td style="padding-top: 10px; padding-bottom: 15px"> {{ post.time_in | date:'d.m.Y' }} </td>
                    <td style="padding-top: 10px; padding-bottom: 15px"> {{ post.text | censor | truncatechars:70 }} </td>
                </tr>
            {% endfor %}
        </table>
        <br/>
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}"><</a>
                <a href="?page=1">1</a>
                {% if page_obj.number == 3 %}
                    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                {% endif %}
                {% if page_obj.number > 3 %}
                    {% if page_obj.number > 4 %}
                        ...
                    {% endif %}
                    <a href="?page={{ page_obj.previous_page_number|add:'-1' }}">{{ page_obj.previous_page_number|add:'-1' }}</a>
                    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                {% endif %}
            {% endif %}

            {{ page_obj.number }}

            {% if page_obj.has_next %}
                {% if page_obj.number|add:'2' < page_obj.paginator.num_pages %}
                    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    <a href="?page={{ page_obj.next_page_number|add:'1' }}">{{ page_obj.next_page_number|add:'1' }}</a>
                    {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
                        ...
                    {% endif %}
                {% endif %}
                {% if page_obj.number|add:'2' == page_obj.paginator.num_pages %}
                    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                {% endif %}
                <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                <a href="?page={{ page_obj.next_page_number }}">></a>
            {% endif %}

        {% endif %}
    {% else %}
        <h2 style="font-family: Georgia;"> Публикаций нет!</h2>
    {% endif %}
    <br/><br/>
{% endblock content %}

NewsPortal/templates/posts_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    Posts/Search
{% endblock title %}

{% block content %}
    <br/>
    <h1 align="center" style="font-family: Georgia;"><strong> Поиск публикаций </strong></h1>
    <hr>
    {% if all %}
        <p style="font-size: 1.3em; font-family: Georgia;">
            Критерии поиска:
        </p>
        <form method="GET">
            {{ filter.form }}
            <input type="submit" value="Найти" style="width:100px" >
        </form>
        <p style="font-size: 1em; font-family: Georgia;">
            <br/>
            Найдено публикаций: {{ filter.qs | length }}
        </p>
        <br/>
        <p style="font-size: 0.8em; font-family: Georgia;">
            Показана страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </p>
        <br/>
        {% if postss %}
            <table style="width: 100%; font-family: Georgia;">
                <tr>
                    <th style="border-bottom: 3px solid #B9B29F; width:40%;padding-bottom: 10px;"> Заголовок </th>
                    <th style="border-bottom: 3px solid #B9B29F; width:15%;padding-bottom: 10px;"> Тип<br/>публикации </th>
                    <th style="border-bottom: 3px solid #B9B29F; width:15%;padding-bottom: 10px;"> Дата<br/>публикации </th>
                    <th style="border-bottom: 3px solid #B9B29F; width:45%;padding-bottom: 10px;"> Содержание </th>
                </tr>
                {% for post in postss %}
                    <tr>
                        <td style="padding-top: 10px; padding-bottom: 15px">
                            <a href="{% url 'post_detail' post.id %}" style="text-decoration: none"> {{ post.head | censor}} </a>
                        </td>
                        <td style="padding-top: 10px; padding-bottom: 15px"> {{ post.get_type_display }} </td>
                        <td style="padding-top: 10px; padding-bottom: 15px"> {{ post.time_in | date:'d.m.Y' }} </td>
                        <td style="padding-top: 10px; padding-bottom: 15px"> {{ post.text | censor | truncatechars:70 }} </td>
                    </tr>
                {% endfor %}
            </table>

            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a href="?{% url_replace page=page_obj.previous_page_number %}"><</a>
                    <a href="?{% url_replace page=1 %}">1</a>
                    {% if page_obj.number == 3 %}
                        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                    {% if page_obj.number > 3 %}
                        {% if page_obj.number > 4 %}
                            ...
                        {% endif %}
                        <a href="?{% url_replace page=page_obj.previous_page_number|add:'-1' %}">{{ page_obj.previous_page_number|add:'-1' }}</a>
                        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                {% endif %}

                {{ page_obj.number }}

                {% if page_obj.has_next %}
                    {% if page_obj.number|add:'2' < page_obj.paginator.num_pages %}
                        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
                        <a href="?{% url_replace page=page_obj.next_page_number|add:'1' %}">{{ page_obj.next_page_number|add:'1' }}</a>
                        {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
                            ...
                        {% endif %}
                    {% endif %}
                    {% if page_obj.number|add:'2' == page_obj.paginator.num_pages %}
                        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
                    {% endif %}
                    <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
                    <a href="?{% url_replace page=page_obj.next_page_number %}">></a>
                {% endif %}
            {% endif %}
        {% else %}
            <p style="font-size: 1em; font-family: Georgia;">
            <br/>
                По указанным параметрам публикаций не найдено!
            </p>
        {% endif %}
    {% else %}
        <h2 style="font-family: Georgia;"> Публикаций нет!</h2>
    {% endif %}
    <br/><br/>
{% endblock content %}